# Generated by Django 5.0.1 on 2024-09-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('name1', models.CharField(default='', max_length=255)),
                ('name2', models.CharField(default='', max_length=255)),
                ('code', models.CharField(default='', max_length=255)),
                ('code1', models.CharField(default='', max_length=255)),
                ('code2', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
