# Generated by Django 5.0.1 on 2024-01-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_register_delete_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='verify',
            field=models.IntegerField(default=0),
        ),
    ]
