# Generated by Django 5.0.1 on 2024-10-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_rename_code_country_label_rename_code1_country_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(default='Pending', max_length=255),
        ),
        migrations.AddField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(default=6354816652, max_length=255),
        ),
    ]
