# Generated by Django 5.0.1 on 2024-01-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0003_register_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(default=''),
        ),
    ]
