# Generated by Django 5.0.1 on 2024-10-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_transactions_status_transactions_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerates',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(default=5033776213, max_length=255),
        ),
    ]
