# Generated by Django 5.0.1 on 2024-01-27 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0004_register_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
