# Generated by Django 5.0.1 on 2024-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0006_transactions_moneyrate_alter_transactions_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(default=9841517063, max_length=255),
        ),
    ]
