# Generated by Django 5.0.1 on 2024-10-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_alter_transactions_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactions',
            name='moneyRate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(default=6716596934, max_length=255),
        ),
    ]
