# Generated by Django 5.0.1 on 2024-01-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0007_exchangerates'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangerates',
            name='fee',
            field=models.FloatField(default=0),
        ),
    ]
