# Generated by Django 5.0.1 on 2024-10-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0008_temporarytransactions_moneyrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(default=5551576236, max_length=255),
        ),
    ]
