# Generated by Django 5.0.1 on 2024-10-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0009_alter_transactions_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactions',
            name='currencyReceivedLabel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='currencySentLabel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactions',
            name='currencyReceivedLabel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactions',
            name='currencySentLabel',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(default=2767716902, max_length=255),
        ),
    ]
