# Generated by Django 5.0.1 on 2024-10-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_temporarytransactions_currencyreceivedlabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(default=4060856281, max_length=255),
        ),
    ]
