# Generated by Django 5.0.1 on 2024-02-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0010_transactions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
