# Generated by Django 5.0.1 on 2024-10-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0011_alter_transactions_trans_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=9002351695, max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='trans_id',
            field=models.CharField(max_length=255),
        ),
    ]
