# Generated by Django 5.0.1 on 2024-02-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0012_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currencyReceived',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='currencySent',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='deliveryBank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='deliveryCash',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='gtb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='polaris',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='savings',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='zenith',
            field=models.BooleanField(default=False),
        ),
    ]
