# Generated by Django 5.0.1 on 2024-10-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0013_register1_alter_temporarytransactions_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=7557048648, max_length=255),
        ),
    ]
