# Generated by Django 5.0.1 on 2024-10-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_alter_temporarytransactions_trans_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=5899413856, max_length=255),
        ),
    ]
