# Generated by Django 5.0.1 on 2024-02-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0014_transactions_trans_date_alter_transactions_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='senderEmail',
            field=models.CharField(default='', max_length=255),
        ),
    ]
