# Generated by Django 5.0.1 on 2024-10-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0015_alter_temporarytransactions_trans_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register1',
            new_name='SilaUser',
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=7644209751, max_length=255),
        ),
    ]
