# Generated by Django 5.0.1 on 2024-04-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0015_transactions_senderemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=255)),
                ('expiration', models.CharField(max_length=255)),
                ('securityCode', models.CharField(max_length=255)),
                ('b_fname', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('streetAd', models.CharField(max_length=255)),
                ('apartment', models.CharField(max_length=255)),
                ('b_city', models.CharField(max_length=255)),
                ('b_region', models.CharField(max_length=255)),
                ('zipcode', models.CharField(max_length=255)),
            ],
        ),
    ]
