# Generated by Django 5.0.1 on 2024-04-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
