# Generated by Django 5.0.1 on 2024-10-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0016_rename_register1_silauser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=2284023335, max_length=255),
        ),
    ]
