# Generated by Django 5.0.1 on 2024-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0017_alter_temporarytransactions_trans_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silauser',
            name='session_identifier',
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=5576670373, max_length=255),
        ),
    ]
