# Generated by Django 5.0.1 on 2024-10-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0018_remove_silauser_session_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='silauser',
            name='crypto_alias',
        ),
        migrations.AlterField(
            model_name='silauser',
            name='address_alias',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='silauser',
            name='identity_alias',
            field=models.CharField(default='SSN', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=7545477861, max_length=255),
        ),
    ]
