# Generated by Django 5.0.1 on 2024-10-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0019_remove_silauser_crypto_alias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='trans_id',
            field=models.CharField(default=9742596142, max_length=255),
        ),
    ]
