# Generated by Django 5.0.1 on 2024-04-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0020_remove_transactions_gtb_remove_transactions_polaris_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255)),
                ('mname', models.CharField(default='', max_length=255)),
                ('lname', models.CharField(max_length=255)),
                ('slname', models.CharField(default='', max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('street', models.CharField(max_length=255)),
                ('street2', models.CharField(default='', max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal', models.CharField(max_length=255)),
            ],
        ),
    ]
