# Generated by Django 5.0.1 on 2024-04-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0021_recepients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepients',
            name='account_email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
