# Generated by Django 5.0.1 on 2024-04-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0023_alter_recepients_mname_alter_recepients_slname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='text_notification',
            field=models.BooleanField(default=False),
        ),
    ]
