# Generated by Django 5.0.1 on 2024-05-04 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0024_register_email_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email_notification',
            field=models.CharField(default='0'),
        ),
        migrations.AlterField(
            model_name='register',
            name='text_notification',
            field=models.CharField(default='0'),
        ),
    ]
