# Generated by Django 5.0.1 on 2024-07-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0025_alter_register_email_notification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneySent', models.FloatField(default='')),
                ('moneyReceived', models.FloatField(default='')),
                ('currencySent', models.CharField(default='', max_length=255)),
                ('currencyReceived', models.CharField(default='', max_length=255)),
                ('fee', models.FloatField(default='')),
                ('total', models.FloatField(default='')),
            ],
        ),
    ]
