# Generated by Django 5.0.1 on 2024-07-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0026_temporarytransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactions',
            name='bankname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='deliveryBank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='deliveryCash',
            field=models.BooleanField(default=False),
        ),
    ]
