# Generated by Django 5.0.1 on 2024-07-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0027_temporarytransactions_bankname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactions',
            name='accountNumber',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='retypeAccountNumber',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='savings',
            field=models.BooleanField(default=False),
        ),
    ]
