# Generated by Django 5.0.1 on 2024-07-29 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0029_temporarytransactions_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='mname',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='slname',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='temporarytransactions',
            name='street',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
