# Generated by Django 5.0.1 on 2024-08-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0030_alter_temporarytransactions_mname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactions',
            name='apartment',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='b_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='b_fname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='b_region',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='cardNumber',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='expiration',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='nickname',
            field=models.CharField(default='none', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='securityCode',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='streetAd',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='zipcode',
            field=models.CharField(default='', max_length=255),
        ),
    ]
