# Generated by Django 5.0.1 on 2024-08-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0031_temporarytransactions_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactions',
            name='auto_id',
            field=models.CharField(default='', verbose_name=7232027388),
        ),
    ]
