# Generated by Django 5.0.1 on 2024-08-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0033_alter_temporarytransactions_auto_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarytransactions',
            name='auto_id',
            field=models.IntegerField(verbose_name=8589351761),
        ),
    ]
