# Generated by Django 5.0.1 on 2024-08-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0034_alter_temporarytransactions_auto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarytransactions',
            name='auto_id',
        ),
    ]
