# Generated by Django 5.0.1 on 2024-08-07 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0035_remove_temporarytransactions_auto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarytransactions',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
