# Generated by Django 5.0.1 on 2024-08-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0036_temporarytransactions_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarytransactions',
            name='userid',
        ),
        migrations.AddField(
            model_name='temporarytransactions',
            name='emailId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
